export interface Speaker {
  name: string;
  company: string;
  image: string;
  xLink?: string;
  imageScale?: string;
}

export const pastSpeakers: Speaker[] = [
  // {
  //   name: "Abhishek Yadav",
  //   company: "Etherspot",
  //   image: "/assets/speakers/Abhishek Yadav - Etherspot.png",
  //   xLink: "https://x.com/abhixh",
  //   imageScale: "h-[150%]",
  // },
  {
    name: "Aditi Polkam",
    company: "Offline Protocol",
    image: "/assets/speakers/Aditi_Polkam.png",
    xLink: "https://x.com//aditipolkam",
    imageScale: "h-[185%]",
  },
  {
    name: "Akash Balasubramani",
    company: "Starkware",
    image: "/assets/speakers/akash_-_starkware-removebg-preview.png",
    xLink: "https://x.com/akashneelesh",
    imageScale: "h-[130%]",
  },
   {
    name: "Archana Bakshi",
    company: "SSV Network",
    image: "/assets/speakers/archana-removebg-preview.png",
    xLink: "https://x.com/0xArchana",
    imageScale: "h-[110%]",
  },
  // {
  //   name: "Aniket Sharma",
  //   company: "Rath Finance",
  //   image: "/assets/speakers/Aniket Sharma - Rath Finance.png",
  //   xLink: "https://x.com/0xaniketsharma",
  //   imageScale: "h-[110%]",
  // },
  {
    name: "Ayush Bhadauria",
    company: "ZisK",
    image: "/assets/speakers/Ayush Bhadauria - ZisK.png",
    xLink: "https://x.com/0xAbix",
    imageScale: "h-[140%]",
  },
  // {
  //   name: "Ayush Bherwani",
  //   company: "MetaMask",
  //   image: "/assets/speakers/Ayush_Bherwani.png",
  //   xLink: "http://x.com/ayushbherwani",
  //   imageScale: "h-[120%]",
  // },
  {
    name: "Denver",
    company: "Devfolio",
    image: "/assets/speakers/Denver Dsouza - Devfolio.png",
    xLink: "https://x.com/denverjude",
    imageScale: "h-[130%]",
  },
  {
    name: "Devansh Mehta",
    company: "Ethereum Foundation",
    image:
      "/assets/speakers/devansh_mehta_-_ethereum_foundation-removebg-preview.png",
    xLink: "https://x.com/devanshmehta",
    imageScale: "h-[115%]",
  },
  {
    name: "Dhaiwat",
    company: "ENS",
    image: "/assets/speakers/dhaiwat.png",
    xLink: "https://x.com/dhaiwat10",
    imageScale: "h-[145%]",
  },
  {
    name: "Didier Krux",
    company: "Devcon",
    image: "/assets/hackathon/mentors/Didier_Mentor-removebg-preview.png",
    xLink: "https://x.com/DidierKrux",
    imageScale: "h-[130%]",
  },
  {
    name: "Heet Tike",
    company: "noice",
    image: "/assets/speakers/heet_tike_-_noice-removebg-preview.png",
    xLink: "https://x.com/heettike",
    imageScale: "h-[120%]",
  },
  {
    name: "Jatin Pandya",
    company: "Canton Foundation",
    image: "/assets/speakers/Jatin_Pandya.png",
    xLink: "https://twitter.com/Jpandya26",
    imageScale: "h-[185%]",
  },
  // {
  //   name: "Jayesh Bhole",
  //   company: "Offchain Labs",
  //   image: "/assets/hackathon/mentors/Jayesh Bhole.png",
  //   xLink: "https://x.com/supremebattak",
  //   imageScale: "h-[125%]",
  // },
  {
    name: "Kanika Mishra",
    company: "USDT Marketplace",
    image: "/assets/speakers/Kanika_Mishra.png",
    xLink: "https://x.com/mishrakanika3",
    imageScale: "h-[140%]",
  },
  // {
  //   name: "Krishang Shah",
  //   company: "Polygon Labs",
  //   image: "/assets/speakers/Krishang_Shah.png",
  //   xLink: "https://x.com/0xkrishang",
  //   imageScale: "h-[130%]",
  // },
  {
    name: "Kunal Gandhi",
    company: "HeyElsa",
    image: "/assets/hackathon/judges/kunal_gandhi-removebg-preview.png",
    xLink: "https://x.com/kunalvg",
    imageScale: "h-[120%] right-[50%]",
  },
   {
    name: "Naina Sachdev",
    company: "dev3pack",
    image: "/assets/speakers/Naina_Sachdev_-_dev3pack-removebg-preview.png",
    xLink: "https://x.com/Nainasachdev11",
    imageScale: "h-[150%]",
  },
  {
    name: "Nandit Mehra",
    company: "Lighthouse",
    image: "/assets/hackathon/judges/Nandit_Judge-removebg-preview.png",
    xLink: "https://x.com/nanditmehra",
    imageScale: "h-[120%]",
  },
  {
    name: "Pareen Lathia",
    company: "Monad Foundation",
    image: "/assets/speakers/Pareen_Lathai.png",
    xLink: "https://x.com/pareen",
  },
  // {
  //   name: "Rahat",
  //   company: "Move Industries",
  //   image: "/assets/speakers/Rahat.png",
  //   xLink: "https://x.com/Rahatcodes",
  //   imageScale: "h-[145%]",
  // },
  {
    name: "Rahul Bhadoriya",
    company: "Dacoit",
    image: "/assets/speakers/Rahul_Bhadoriya.png",
    xLink: "https://x.com/rahulbhadoriya",
    imageScale: "h-[130%]",
  },
  {
    name: "Reet Batra",
    company: "",
    image: "/assets/hackathon/judges/Reet_Batra-removebg-preview.png",
    xLink: "https://x.com/reet_batra",
    imageScale: "h-[120%]",
  },
    {
    name: "Robin Roy",
    company: "Avail",
    image: "/assets/speakers/Robin_Roy_-_Avail-removebg-preview.png",
    xLink: "https://x.com/robin_rrtx",
    imageScale: "h-[125%]",
  },
  // {
  //   name: "Sahil",
  //   company: "Quicknode",
  //   image: "/assets/speakers/Sahil_Sen_-_Quicknode-removebg-preview.png",
  //   xLink: "https://x.com/sensahil",
  //   imageScale: "h-[125%]",
  // },
  // {
  //   name: "Sebastian Burkhard",
  //   company: "Yodl Pay",
  //   image: "/assets/speakers/Sebastian_Burkhard.png",
  //   xLink: "https://x.com/yodl_meister",
  //   imageScale: "h-[120%]",
  // },
  {
    name: "Shiv Bhonde ",
    company: "BuidlGuidl",
    image: "/assets/speakers/Shiv_Bhonde.png",
    xLink: "https://x.com/ShivBhonde",
    imageScale: "h-[128%]",
  },
   {
    name: "Shubham Bhandari",
    company: "Manta Network",
    image: "/assets/speakers/Shubham_Bhandari_-_Manta_Network-removebg-preview.png",
    xLink: "https://x.com/Shubhamb",
    imageScale: "h-[128%]",
  },
  // {
  //   name: "Shyam Sridhar",
  //   company: "Ethereum Foundation",
  //   image: "/assets/speakers/Shyam_Sridhar2.png",
  //   xLink: "https://x.com/ShyamSridhar7",
  //   imageScale: "h-[130%]",
  // },
  
  // {
  //   name: "Siddharth Biju",
  //   company: "",
  //   image: "/assets/speakers/Siddharth Biju.png",
  //   xLink: "https://x.com/sidbharth",
  //   imageScale: "h-[120%]",
  // },
  {
    name: "Smit Khakhkhar",
    company: "CoinList",
    image: "/assets/hackathon/judges/Smit_Judge-removebg-preview.png",
    xLink: "https://x.com/0xSmit",
    imageScale: "h-[110%]",
  },
    {
    name: "Sweta Shaw",
    company: "Own Finance",
    image: "/assets/hackathon/judges/Sweta_Judge-removebg-preview.png",
    xLink: "https://x.com/swetashaw_",
    imageScale: "h-[125%]",
  },
  {
    name: "Vanshika Srivastava",
    company: "Gnosis",
    image: "/assets/hackathon/judges/Vanshika_Judge-removebg-preview.png",
    xLink: "https://x.com/ThisisVanshika",
    imageScale: "h-[118%]",
  },
  {
    name: "Vijay",
    company: "Fileverse",
    image: "/assets/speakers/vijay_-_fileverse-removebg-preview.png",
    xLink: "https://x.com/0x6b8",
    imageScale: "h-[135%]",
  }
];

export const homeSpeakers: Speaker[] = [
  {
    name: "Aditi Polkam",
    company: "Offline Protocol",
    image: "/assets/speakers/Aditi_Polkam.png",
    xLink: "https://x.com//aditipolkam",
    imageScale: "h-[185%]",
  },
  {
    name: "Akash Balasubramani",
    company: "Starkware",
    image: "/assets/speakers/akash_-_starkware-removebg-preview.png",
    xLink: "https://x.com/akashneelesh",
    imageScale: "h-[130%]",
  },
  {
    name: "Ayush Bherwani",
    company: "MetaMask",
    image: "/assets/speakers/Ayush_Bherwani.png",
    xLink: "http://x.com/ayushbherwani",
    imageScale: "h-[120%]",
  },
  {
    name: "Devansh Mehta",
    company: "Ethereum Foundation",
    image:
      "/assets/speakers/devansh_mehta_-_ethereum_foundation-removebg-preview.png",
    xLink: "https://x.com/devanshmehta",
    imageScale: "h-[115%]",
  },
  {
    name: "Dhaiwat",
    company: "ENS",
    image: "/assets/speakers/dhaiwat.png",
    xLink: "https://x.com/dhaiwat10",
    imageScale: "h-[145%]",
  },
  {
    name: "Heet Tike",
    company: "noice",
    image: "/assets/speakers/heet_tike_-_noice-removebg-preview.png",
    xLink: "https://x.com/heettike",
    imageScale: "h-[120%]",
  },
  {
    name: "Jatin Pandya",
    company: "",
    image: "/assets/speakers/Jatin_Pandya.png",
    xLink: "https://twitter.com/Jpandya26",
    imageScale: "h-[185%]",
  },
  {
    name: "Kanika Mishra",
    company: "USDT Marketplace",
    image: "/assets/speakers/Kanika_Mishra.png",
    xLink: "https://x.com/mishrakanika3",
    imageScale: "h-[140%]",
  },
  {
    name: "Krishang Shah",
    company: "Polygon Labs",
    image: "/assets/speakers/Krishang_Shah.png",
    xLink: "https://x.com/0xkrishang",
    imageScale: "h-[130%]",
  },
  {
    name: "Pareen Lathia",
    company: "Monad Foundation",
    image: "/assets/speakers/Pareen_Lathai.png",
    xLink: "https://x.com/pareen",
  },
  {
    name: "Rahat",
    company: "Move Industries",
    image: "/assets/speakers/Rahat.png",
    xLink: "https://x.com/Rahatcodes",
    imageScale: "h-[145%]",
  },
  {
    name: "Rahul Bhadoriya",
    company: "Dacoit",
    image: "/assets/speakers/Rahul_Bhadoriya.png",
    xLink: "https://x.com/rahulbhadoriya",
    imageScale: "h-[130%]",
  },
  {
    name: "Sebastian Burkhard",
    company: "Yodl Pay",
    image: "/assets/speakers/Sebastian_Burkhard.png",
    xLink: "https://x.com/yodl_meister",
    imageScale: "h-[120%]",
  },
  {
    name: "Shiv Bhonde ",
    company: "BuidlGuidl",
    image: "/assets/speakers/Shiv_Bhonde.png",
    xLink: "https://x.com/ShivBhonde",
    imageScale: "h-[128%]",
  },
  {
    name: "Shyam Sridhar",
    company: "Ethereum Foundation",
    image: "/assets/speakers/Shyam_Sridhar2.png",
    xLink: "https://x.com/ShyamSridhar7",
    imageScale: "h-[130%]",
  },
  {
    name: "Vanshika Srivastava",
    company: "Gnosis",
    image: "/assets/hackathon/judges/Vanshika_Judge-removebg-preview.png",
    xLink: "https://x.com/ThisisVanshika",
    imageScale: "h-[118%]",
  },
];
export const conferenceSpeakers: Speaker[] = [
  {
    name: "Abhishek Yadav",
    company: "Etherspot",
    image: "/assets/speakers/Abhishek Yadav - Etherspot.png",
    xLink: "https://x.com/abhixh",
    imageScale: "h-[150%]",
  },
  {
    name: "Aditi Polkam",
    company: "Offline Protocol",
    image: "/assets/speakers/Aditi_Polkam.png",
    xLink: "https://x.com//aditipolkam",
    imageScale: "h-[185%]",
  },
  {
    name: "Akash Balasubramani",
    company: "Starkware",
    image: "/assets/speakers/akash_-_starkware-removebg-preview.png",
    xLink: "https://x.com/akashneelesh",
    imageScale: "h-[130%]",
  },
  {
    name: "Ale Marin",
    company: "NERDCONF",
    image: "/assets/speakers/ALE_MARIN_NERDCONF-removebg-preview.png",
    xLink: "https://x.com/AleeeM1",
    imageScale: "h-[120%]",
  },
  {
    name: "Aniket",
    company: "Remix Labs",
    image: "/assets/speakers/Aniket_Remix_Judge-removebg-preview.png",
    xLink: "https://x.com/AniketEngg",
    imageScale: "h-[125%]",
  },
  {
    name: "Aniket Sharma",
    company: "Rath Finance",
    image: "/assets/speakers/Aniket Sharma - Rath Finance.png",
    xLink: "https://x.com/0xaniketsharma",
    imageScale: "h-[110%]",
  },
  {
    name: "Archana Bakshi",
    company: "SSV Network",
    image: "/assets/speakers/archana-removebg-preview.png",
    xLink: "https://x.com/0xArchana",
    imageScale: "h-[110%]",
  },
  {
    name: "Ayush Bhadauria",
    company: "ZisK",
    image: "/assets/speakers/Ayush Bhadauria - ZisK.png",
    xLink: "https://x.com/0xAbix",
    imageScale: "h-[140%]",
  },
  {
    name: "Ayush Bherwani",
    company: "MetaMask",
    image: "/assets/speakers/Ayush_Bherwani.png",
    xLink: "http://x.com/ayushbherwani",
    imageScale: "h-[120%]",
  },
  {
    name: "Denver",
    company: "Devfolio",
    image: "/assets/speakers/Denver Dsouza - Devfolio.png",
    xLink: "https://x.com/denverjude",
    imageScale: "h-[130%]",
  },
  {
    name: "Devansh Mehta",
    company: "Ethereum Foundation",
    image: "/assets/speakers/devansh_mehta_-_ethereum_foundation-removebg-preview.png",
    xLink: "https://x.com/devanshmehta",
    imageScale: "h-[115%]",
  },
  {
    name: "Dhaiwat",
    company: "ENS",
    image: "/assets/speakers/dhaiwat.png",
    xLink: "https://x.com/dhaiwat10",
    imageScale: "h-[145%]",
  },
  {
    name: "Heet Tike",
    company: "noice",
    image: "/assets/speakers/heet_tike_-_noice-removebg-preview.png",
    xLink: "https://x.com/heettike",
    imageScale: "h-[120%]",
  },
  {
    name: "Iptisha",
    company: "Circulox",
    image: "/assets/speakers/Iptisha_-_Circulox-removebg-preview.png",
    xLink: "https://x.com/iptishax",
    imageScale: "h-[148%]",
  },
  {
    name: "Jatin Pandya",
    company: "Canton Foundation",
    image: "/assets/speakers/Jatin_Pandya.png",
    xLink: "https://twitter.com/Jpandya26",
    imageScale: "h-[185%]",
  },
  {
    name: "Jobin Ayathil",
    company: "TEN Protocol",
    image: "/assets/speakers/Jobin_-_ten-removebg-preview.png",
    xLink: "https://x.com/0xjba",
    imageScale: "h-[165%]",
  },
  {
    name: "Kanika Mishra",
    company: "USDT Marketplace",
    image: "/assets/speakers/Kanika_Mishra.png",
    xLink: "https://x.com/mishrakanika3",
    imageScale: "h-[140%]",
  },
  {
    name: "Krishang Shah",
    company: "Polygon Labs",
    image: "/assets/speakers/Krishang_Shah.png",
    xLink: "https://x.com/0xkrishang",
    imageScale: "h-[130%]",
  },
   {
    name: "Kunal Gandhi",
    company: "HeyElsa",
    image: "/assets/hackathon/judges/kunal_gandhi-removebg-preview.png",
    xLink: "https://x.com/kunalvg",
    imageScale: "h-[120%] right-[50%]",
  },
   {
    name: "Naina Sachdev",
    company: "dev3pack",
    image: "/assets/speakers/Naina_Sachdev_-_dev3pack-removebg-preview.png",
    xLink: "https://x.com/nainasachdev_?s=11",
    imageScale: "h-[150%]",
  },
  {
    name: "Pareen Lathia",
    company: "Monad Foundation",
    image: "/assets/speakers/Pareen_Lathai.png",
    xLink: "https://x.com/pareen",
  },
  // {
  //   name: "Rahat",
  //   company: "Move Industries",
  //   image: "/assets/speakers/Rahat.png",
  //   xLink: "https://x.com/Rahatcodes",
  //   imageScale: "h-[145%]",
  // },
   {
    name: "Rachit",
    company: "Touch Grass Podcast",
    image: "/assets/speakers/Rachit.png",
    xLink: "https://x.com/rachit",
    imageScale: "h-[115%]",
  },
  {
    name: "Rahul Bhadoriya",
    company: "Dacoit",
    image: "/assets/speakers/Rahul_Bhadoriya.png",
    xLink: "https://x.com/rahulbhadoriya",
    imageScale: "h-[130%]",
  },
  {
    name: "Robin Roy",
    company: "Avail",
    image: "/assets/speakers/Robin_Roy_-_Avail-removebg-preview.png",
    xLink: "https://x.com/robin_rrtx",
    imageScale: "h-[125%]",
  },
  // {
  //   name: "Sahil",
  //   company: "Quicknode",
  //   image: "/assets/speakers/Sahil_Sen_-_Quicknode-removebg-preview.png",
  //   xLink: "https://x.com/sensahil",
  //   imageScale: "h-[125%]",
  // },
  {
    name: "Sebastian Burkhard",
    company: "Yodl Pay",
    image: "/assets/speakers/Sebastian_Burkhard.png",
    xLink: "https://x.com/yodl_meister",
    imageScale: "h-[120%]",
  },
  {
    name: "Sharvil",
    company: "CapX",
    image: "/assets/speakers/Sharvil_-_Capx-removebg-preview.png",
    xLink: "https://x.com/0xsharvil",
    imageScale: "h-[138%]",
  },
  {
    name: "Shiv Bhonde ",
    company: "BuidlGuidl",
    image: "/assets/speakers/Shiv_Bhonde.png",
    xLink: "https://x.com/ShivBhonde",
    imageScale: "h-[128%]",
  },
   {
    name: "Sharvil",
    company: "CapX",
    image: "/assets/speakers/Sharvil_-_Capx-removebg-preview.png",
    xLink: "https://x.com/0xsharvil",
    imageScale: "h-[138%]",
  },
  {
    name: "Shubham Bhandari",
    company: "Manta Network",
    image: "/assets/speakers/Shubham_Bhandari_-_Manta_Network-removebg-preview.png",
    xLink: "https://x.com/Shubhamb",
    imageScale: "h-[128%]",
  },
  {
    name: "Shyam Sridhar",
    company: "Ethereum Foundation",
    image: "/assets/speakers/Shyam_Sridhar2.png",
    xLink: "https://x.com/ShyamSridhar7",
    imageScale: "h-[130%]",
  },
  {
    name: "Siddharth Biju",
    company: "",
    image: "/assets/speakers/Siddharth Biju.png",
    xLink: "https://x.com/sidbharth",
    imageScale: "h-[120%]",
  },
  {
    name: "Sweta Shaw",
    company: "Own Finance",
    image: "/assets/speakers/Sweta_Judge-removebg-preview.png",
    xLink: "https://x.com/swetashaw_",
    imageScale: "h-[125%]",
  },
  {
    name: "Tanay",
    company: "PropellerHeads",
    image: "/assets/speakers/Tanay_-_PropellerHeads-removebg-preview.png",
    xLink: "https://x.com/tanayjain",
    imageScale: "h-[150%]",
  },
  {
    name: "Tomas Octavio",
    company: "NERDCONF",
    image: "/assets/speakers/TOMAS_OCTAVIO_NERDCONF-removebg-preview.png",
    xLink: "https://x.com/tomasoctavio_",
    imageScale: "h-[120%]",
  },
  {
    name: "Vijay",
    company: "Fileverse",
    image: "/assets/speakers/vijay_-_fileverse-removebg-preview.png",
    xLink: "https://x.com/0x6b8",
    imageScale: "h-[135%]",
  },
  {
    name: "Vishal Singh",
    company: "ZippelLabs",
    image: "/assets/speakers/Vishal_Mentor-removebg-preview.png",
    xLink: "https://x.com/thisvishalsingh",
    imageScale: "h-[110%]",
  }
];
